version: '3.8'

services:
  dns:
    build:
      context: ./dns
      dockerfile: dockerfile
    image: tniromin2/dns-server:latest
    network_mode: host

  dhcp:
    build:
      context: ./dhcp
      dockerfile: dockerfile
    image: tniromin2/dhcp-server:latest
    network_mode: dhcp-net
    cap_add:
      - NET_ADMIN

  squid:
    build:
      context: ./squid
      dockerfile: dockerfile
    image: tniromin2/squid-proxy:latest
    ports:
      - "3128:3128"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m

  dhcp-client:
    build:
      context: ./dhcp-client
      dockerfile: dockerfile
    image: tniromin2/dhcp-client:latest
    network_mode: dhcp-net
    cap_add:
      - NET_ADMIN
    depends_on:
      - dhcp  

networks:
  dhcp-net:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam: 
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
